CREATE TABLE public.families (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) with time zone NOT NULL,
                                 name character varying(255) NOT NULL,
                                 updated_at timestamp(6) with time zone NOT NULL
);

ALTER TABLE public.families
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.families_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

CREATE TABLE public.family_members (
                                       id bigint NOT NULL,
                                       created_at timestamp(6) with time zone NOT NULL,
                                       name character varying(255) NOT NULL,
                                       role character varying(255) NOT NULL,
                                       updated_at timestamp(6) with time zone NOT NULL,
                                       family_id bigint,
                                       CONSTRAINT family_members_role_check CHECK (
                                           (role)::text = ANY (ARRAY['DAD','MOM','CHILD'])
)
    );

ALTER TABLE public.family_members
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.family_members_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

ALTER TABLE ONLY public.families
    ADD CONSTRAINT families_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.family_members
    ADD CONSTRAINT family_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.family_members
    ADD CONSTRAINT fkeynpxqr1l03689buyid3e1d8l FOREIGN KEY (family_id)
    REFERENCES public.families(id);
