CREATE TABLE public.todos (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255),
    due_date timestamp(6) with time zone,
    completed boolean NOT NULL,
    family_id bigint,
    family_member_id bigint
);

ALTER TABLE public.todos
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.todos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.todos
    ADD CONSTRAINT todos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.todos
    ADD CONSTRAINT fk_todos_family FOREIGN KEY (family_id)
    REFERENCES public.families(id);

ALTER TABLE ONLY public.todos
    ADD CONSTRAINT fk_todos_family_member FOREIGN KEY (family_member_id)
    REFERENCES public.family_members(id);
