CREATE TABLE public.activities (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255),
    location character varying(255),
    day date NOT NULL,
    start_time time(6),
    end_time time(6),
    family_id bigint
);

ALTER TABLE public.activities
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT activities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.activities
    ADD CONSTRAINT fk_activities_family FOREIGN KEY (family_id)
    REFERENCES public.families(id);

CREATE TABLE public.activity_participants_mapping (
    activity_id bigint NOT NULL,
    participants_id bigint NOT NULL
);

ALTER TABLE ONLY public.activity_participants_mapping
    ADD CONSTRAINT activity_participants_mapping_pkey PRIMARY KEY (activity_id, participants_id);

ALTER TABLE ONLY public.activity_participants_mapping
    ADD CONSTRAINT fk_apm_activity FOREIGN KEY (activity_id)
    REFERENCES public.activities(id);

ALTER TABLE ONLY public.activity_participants_mapping
    ADD CONSTRAINT fk_apm_family_member FOREIGN KEY (participants_id)
    REFERENCES public.family_members(id);
