CREATE TABLE public.family_accounts (
    id bigint NOT NULL,
    public_slug character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    family_id bigint NOT NULL,
    last_login_at timestamp(6) with time zone,
    failed_login_attempts integer NOT NULL DEFAULT 0,
    locked boolean NOT NULL DEFAULT false
);

ALTER TABLE public.family_accounts
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.family_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.family_accounts
    ADD CONSTRAINT family_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.family_accounts
    ADD CONSTRAINT family_accounts_public_slug_key UNIQUE (public_slug);

ALTER TABLE ONLY public.family_accounts
    ADD CONSTRAINT family_accounts_family_id_key UNIQUE (family_id);

ALTER TABLE ONLY public.family_accounts
    ADD CONSTRAINT fk_family_accounts_family FOREIGN KEY (family_id)
    REFERENCES public.families(id);
